services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  uforwarder:
    build:
      context: ./UForwarderConsumer/UForwarderConsumer
      dockerfile: Dockerfile

    container_name: uforwarder

    ports:
    - "9091:9091"

    depends_on:
      - kafka
      - redis

    environment:
      Kafka__BootstrapServers: kafka:29092
      Kafka__Topic: orders.v1
      Kafka__DlqTopic: uforwarder.dlq
      Kafka__GroupId: uforwarder-group
      Redis__ConnectionString: redis:6379

  retryworker:
    build:
      context: ./UForwarderConsumer/RetryWorker
      dockerfile: Dockerfile

    container_name: retryworker

    depends_on:
      - kafka
      - redis

    environment:
      Kafka__BootstrapServers: kafka:29092
      Kafka__Topic: orders.v1
      Kafka__DlqTopic: uforwarder.dlq
      Redis__ConnectionString: redis:6379

  tokenrefiller:
    build:
      context: ./UForwarderConsumer/TokenRefiller
      dockerfile: Dockerfile

    container_name: tokenrefiller

    depends_on:
      - redis

    environment:
      Redis__ConnectionString: redis:6379
      TokenRefill__RefillIntervalSeconds: 120
      TokenRefill__MaxTokens: 10
      TokenRefill__RefillAmount: 10
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - uforwarder

  grafana:
    image: grafana/grafana:latest
    container_name: grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus